# Ash.Query.Function.Error â€” ash v3.4.8

Project: ash v3.4.8

## Table of Contents

- [ __ View Source ](external_link) Ash.Query.Function.Error (ash v3.4.8)
- __ Summary
  - Functions
- __ Functions
- args()

__

Search documentation of ash __ __

__ Settings

#  [ __ View Source ](external_link) Ash.Query.Function.Error (ash v3.4.8)

If the predicate is truthy, the provided exception is raised with the provided values.

This exception is not "raised" in the Elixir sense, but the entire expression fails to evaluate with the given error. Various data layers will handle this differently.

#  __ Summary

##  Functions

args()

Callback implementation for [`Ash.Query.Function.args/0`](external_link).

#  __ Functions

__ Link to this function

# args()

[ __ View Source ](external_link)

Callback implementation for [`Ash.Query.Function.args/0`](external_link).
